### ISSUE TITLE
How to use this theme ?

### ISSUE THREAD

**Issue by jilen** [zk-phi/lenlen-theme#1]
Actually I have install it from melpa but don't know how to active it...

**Comment by zk-phi** [comment]
didn't this work?

```
(load-theme 'lenlen-theme t)
```

**Comment by jilen** [comment]
It complains error: Unable to find theme file for `lenlen-theme'

**Comment by zk-phi** [comment]
how about this ?

```
(require 'lenlen-theme)
```

**Comment by jilen** [comment]
That's it! Thanks
